
#line 3 "lex.sfyy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer sfyy_create_buffer
#define yy_delete_buffer sfyy_delete_buffer
#define yy_flex_debug sfyy_flex_debug
#define yy_init_buffer sfyy_init_buffer
#define yy_flush_buffer sfyy_flush_buffer
#define yy_load_buffer_state sfyy_load_buffer_state
#define yy_switch_to_buffer sfyy_switch_to_buffer
#define yyin sfyyin
#define yyleng sfyyleng
#define yylex sfyylex
#define yylineno sfyylineno
#define yyout sfyyout
#define yyrestart sfyyrestart
#define yytext sfyytext
#define yywrap sfyywrap
#define yyalloc sfyyalloc
#define yyrealloc sfyyrealloc
#define yyfree sfyyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE sfyyrestart(sfyyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t sfyyleng;

extern FILE *sfyyin, *sfyyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up sfyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up sfyytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via sfyyrestart()), so that the user can continue scanning by
	 * just pointing sfyyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when sfyytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t sfyyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow sfyywrap()'s to do buffer switches
 * instead of setting up a fresh sfyyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void sfyyrestart (FILE *input_file  );
void sfyy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE sfyy_create_buffer (FILE *file,int size  );
void sfyy_delete_buffer (YY_BUFFER_STATE b  );
void sfyy_flush_buffer (YY_BUFFER_STATE b  );
void sfyypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void sfyypop_buffer_state (void );

static void sfyyensure_buffer_stack (void );
static void sfyy_load_buffer_state (void );
static void sfyy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER sfyy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE sfyy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE sfyy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE sfyy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *sfyyalloc (yy_size_t  );
void *sfyyrealloc (void *,yy_size_t  );
void sfyyfree (void *  );

#define yy_new_buffer sfyy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        sfyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            sfyy_create_buffer(sfyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        sfyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            sfyy_create_buffer(sfyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define sfyywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *sfyyin = (FILE *) 0, *sfyyout = (FILE *) 0;

typedef int yy_state_type;

extern int sfyylineno;

int sfyylineno = 1;

extern char *sfyytext;
#define yytext_ptr sfyytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up sfyytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	sfyyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 42
#define YY_END_OF_BUFFER 43
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[398] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   43,   41,
       34,   33,   41,   39,   39,   40,   36,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   36,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   34,    0,   32,   39,
       37,   39,   36,   35,   39,   35,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       30,   39,    3,   39,   39,    3,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,

       30,   39,   12,   12,   12,   39,   39,   39,   39,   39,
       39,   39,   38,   36,   39,   35,   35,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,    3,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   35,   39,   39,
       39,   39,   39,   39,   39,   36,   39,   39,   35,   35,
       35,   39,   39,   11,   39,    6,    9,   39,   39,    4,
       39,    7,   39,   39,   39,   39,   39,   16,   39,   39,
        3,   39,   39,   39,   11,   39,    6,    9,   39,   39,

        4,   39,    7,   39,   39,   39,   39,   39,   16,   39,
       39,   35,   35,   39,   39,   39,   39,   39,   39,   39,
       36,   39,   35,   35,   35,   39,   15,    1,   39,   39,
       39,   39,   39,   39,    8,   39,    5,   39,   39,   39,
       39,   15,    1,   39,   39,   39,   39,   39,   39,    8,
       39,    5,   39,   39,   39,   12,   12,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   35,   39,   39,   39,
       39,   17,   39,   13,   39,   39,   39,   39,   39,   39,
       39,   39,   17,   39,   13,   39,   39,   35,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   14,   39,   39,

       39,   39,   39,   39,   39,   39,   14,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   18,   39,   39,   10,
       31,   39,   39,   39,   39,   39,   39,   10,   31,   39,
       39,   39,   39,   39,   39,   39,   35,   39,    2,   39,
       39,   39,   39,   39,    2,   39,   39,   39,   39,   39,
       39,   35,   39,   39,   25,   39,   39,   39,   39,   39,
       39,   39,   39,   35,   39,   26,   39,   39,   22,   39,
       24,   39,   23,   39,   39,   39,   39,   39,   19,   20,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       27,   39,   28,   39,   21,   29,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    6,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,   10,    1,
        1,    1,    1,    1,   11,   11,   11,   11,   11,   11,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   12,   23,   24,   25,   26,
       27,   28,   12,   29,   30,   31,   32,   33,   34,   35,
       36,   12,   37,    1,   38,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[39] =
    {   0,
        1,    1,    1,    1,    2,    2,    1,    2,    2,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1
    } ;

static yyconst flex_int16_t yy_base[401] =
    {   0,
        0,    0,   38,    0,   69,    0,   72,   88,  716,  717,
      713,  717,  711,  705,    0,  717,  115,  703,   73,   89,
       84,  682,  683,   82,  687,  680,   64,   64,  689,  679,
      691,  130,  145,  154,   83,  174,   82,  111,  135,   99,
      147,  163,  137,  157,  161,  196,  183,  192,  187,  191,
      180,  673,  138,  183,  200,  677,  700,  698,  717,    0,
      692,  691,  220,  232,  214,  689,  236,  673,  674,  668,
      664,  671,  177,  666,  660,  663,  671,  662,  206,  159,
        0,  663,  218,  246,  657,  677,  667,  242,  223,  229,
      238,  247,  253,  248,  244,  251,  261,  257,  270,  262,

      654,  263,  673,  289,  294,  651,  262,  652,  278,  651,
      653,  655,  668,  304,  299,  318,  302,  322,  648,  657,
      641,  641,  654,  648,  651,  645,  645,  642,  646,  644,
      641,  648,  643,  643,  626,  636,  308,  344,  628,  311,
      272,  310,  312,  296,  324,  327,  321,  325,  340,   93,
      328,  343,  352,  349,  351,  196,  348,  374,  643,  349,
      642,  632,  640,  624,  635,  378,  641,  641,  386,  639,
      367,  629,  612,    0,  617,    0,  622,  617,  613,    0,
      614,    0,  237,  622,  613,  602,  603,    0,  618,  618,
      387,  370,  380,  377,  605,  379,  604,  388,  386,  603,

      602,  387,  601,  400,  395,  394,  390,  396,  600,  403,
      410,  432,  425,  598,  598,  596,  608,  594,  618,  608,
      428,  429,  444,  615,  611,  589,    0,    0,  592,  595,
      597,  589,  585,  578,    0,  595,    0,  606,  581,  604,
      412,  579,  578,  427,  416,  425,  438,  577,  436,  576,
      440,  575,  461,  574,  463,  593,  464,  583,  575,  581,
      593,  579,  582,  565,  586,  468,  584,  562,  572,  559,
      575,    0,  583,    0,  582,  555,  580,  560,  448,  456,
      450,  466,  554,  477,  553,  478,  479,  572,  551,  565,
      549,  561,  547,  558,  543,  480,  567,    0,  545,  535,

      554,  545,  537,  545,  538,  543,  535,  460,  462,  480,
      530,  531,  528,  533,  526,  541,    0,  549,  491,    0,
        0,  538,  533,  532,  528,  523,  532,  521,  520,  475,
      530,  525,  528,  520,  526,  514,  534,  535,    0,  521,
      514,  520,  519,  518,  506,  505,  506,  503,  506,  501,
      511,  520,  509,  508,    0,  506,  519,  493,  496,  491,
      498,  489,  488,    0,  512,    0,  498,  484,    0,  509,
        0,  482,    0,  482,  474,  474,  480,  474,    0,    0,
      478,  476,  403,  357,  349,  323,  313,  293,  291,  217,
        0,  166,    0,  143,    0,    0,  717,  509,  140,   97

    } ;

static yyconst flex_int16_t yy_def[401] =
    {   0,
      397,    1,  397,    3,    1,    5,    1,    1,  397,  397,
      397,  397,  398,  399,  399,  397,  399,  399,   17,   17,
       17,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  400,  400,  400,   34,  400,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   17,   46,   46,   46,   17,
      399,  399,  399,  399,  399,  399,  397,  398,  397,  399,
      399,  399,   17,  399,   63,   64,   63,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,   63,   34,   36,  399,   84,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   63,   63,   63,  399,  399,  399,  399,  399,
      399,  399,  399,   63,  114,  114,  116,  114,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  114,   84,  138,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   64,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  116,   64,
      169,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,  169,  212,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  212,  223,   64,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,  169,  169,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,   36,   36,
       36,   36,   36,   36,   36,   36,   36,  158,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,

      399,  399,  399,  399,  399,  399,   36,   36,   36,   36,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,   36,   36,   36,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,   36,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,    0,  397,  397,  397

    } ;

static yyconst flex_int16_t yy_nxt[756] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   16,
       19,   15,   15,   20,   19,   19,   21,   19,   19,   22,
       23,   24,   15,   25,   15,   15,   26,   27,   28,   29,
       30,   15,   31,   15,   15,   15,   16,   16,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   16,   32,   33,
       15,   34,   32,   32,   35,   32,   32,   36,   37,   38,
       33,   39,   33,   33,   40,   41,   42,   43,   44,   33,
       45,   33,   33,   33,   16,   16,   46,   78,   60,   47,
       65,   79,   48,   47,   47,   49,   47,   47,   50,   60,
       76,   65,   77,   51,   60,   72,   65,   52,   85,   84,

       53,   54,   55,   56,   50,   67,   85,   73,   91,   51,
       85,  204,   68,   52,   89,   69,   53,   54,   55,   56,
       62,   85,   63,   64,   92,   65,   95,   85,   65,   65,
       65,   65,   65,   65,   60,   60,   93,   83,   64,   85,
       84,   60,   60,   84,   84,   84,   84,   84,   84,   60,
       60,  109,   86,   60,  100,   79,   94,   60,   60,   60,
      396,   83,   64,   85,   84,   85,   60,   84,   84,   84,
       87,   84,   84,   96,  102,   97,   98,   88,   60,   60,
       99,   86,   60,  101,  134,   85,   60,  135,   60,   85,
      104,   85,   60,   72,  104,  124,   60,   60,   65,  104,

       80,  395,   90,  103,  110,  107,  104,  125,  105,  104,
      104,  104,  104,  104,  104,   68,  106,  111,   69,   60,
      131,  115,   69,   60,   85,  137,   81,  114,  210,  132,
      115,  133,  394,  115,  115,  115,  115,  115,  115,  116,
       66,   60,  117,  115,  141,  117,  117,  117,  117,  117,
      117,   85,  118,  137,  233,  142,  138,   85,  234,  138,
      138,  138,  138,  138,  138,  140,   85,  143,  144,   85,
       85,  145,   85,  147,  148,   85,   85,  149,  150,   85,
      160,   85,  151,  146,  152,   85,  157,  155,  195,   85,
      156,   85,  125,  153,   60,  154,  115,  158,   85,   60,

       85,  115,  158,  130,   60,  162,  167,   60,  393,  171,
      118,  166,  198,   60,  167,  191,  392,  167,  167,  167,
      167,  167,  167,  168,   85,  169,  170,   60,  171,  167,
      391,  171,  171,  171,  171,  171,  171,  194,   85,   85,
       85,  196,  197,  201,  200,  199,  202,  205,  390,   85,
      172,  191,   85,   85,  192,   85,   85,  192,  192,  192,
      192,  192,  192,  203,  206,  207,  208,  209,   85,  211,
      178,   85,   60,  389,  224,  215,   85,   85,   64,   85,
       85,  212,  388,   62,  213,  221,   64,  213,  213,  213,
      213,  213,  213,  223,   86,   64,  224,  241,   85,  224,

      224,  224,  224,  224,  224,   85,  243,   85,   85,  244,
      242,  245,  250,  247,   85,   85,   85,  248,   85,  251,
      254,  249,   85,   85,   85,  252,  255,  387,   85,  253,
       60,   85,  257,   62,  265,  221,  266,  281,   85,  256,
       85,  279,  257,  282,   85,  257,  257,  257,  257,  257,
      257,  267,  280,   85,  267,   85,  286,  267,  267,  267,
      267,  267,  267,  283,   85,  276,   85,  278,   85,   60,
      285,  224,  288,  265,  308,  297,   85,  307,   85,  310,
      309,  302,  303,  305,   85,  318,  328,  319,   85,   85,
       85,   85,  345,  386,   85,  330,  318,  329,  338,  385,

      384,  383,  382,   85,  381,   85,   85,   85,   85,   58,
       58,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  360,  359,  358,   85,  357,  356,  355,  354,  353,
      318,  352,  351,  350,  349,  348,  347,  346,   85,   85,
      344,  343,  342,  341,  340,  339,  337,  336,  335,  334,
      333,  332,  331,   85,  327,  326,  325,  324,  323,  322,
      321,  320,  265,  317,  316,  315,  314,  313,  312,  311,
      225,   85,   85,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  170,  296,  295,  294,  293,  292,  291,  290,

      289,  288,  287,   85,   85,  284,   85,   85,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,   60,
       60,  264,  263,  262,  261,  260,  259,  258,   85,   85,
       85,  246,   85,   85,  240,  239,  238,  237,  236,  235,
      232,  231,  230,  229,  228,  227,  226,  225,  222,   64,
      220,  219,  218,  217,  216,  214,  193,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  175,  174,  173,  113,  165,  164,  163,  161,
      159,  158,   85,  139,   86,   85,  136,  130,  129,  128,
      127,  126,  123,  122,  121,  120,  119,   60,  113,   61,

       59,   57,  112,  108,   82,   81,   80,   75,   74,   71,
       70,   66,   61,   59,   57,  397,    9,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397
    } ;

static yyconst flex_int16_t yy_chk[756] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,   28,   19,    5,
       19,   28,    5,    5,    5,    5,    5,    5,    7,   21,
       27,   21,   27,    7,   20,   24,   20,    7,  400,   35,

        7,    7,    7,    7,    8,   20,   35,   24,   37,    8,
       37,  150,   20,    8,   35,   21,    8,    8,    8,    8,
       17,  150,   17,   17,   38,   17,   40,   40,   17,   17,
       17,   17,   17,   17,   32,   32,   38,   32,   32,   38,
       32,  399,   32,   32,   32,   32,   32,   32,   32,   33,
       33,   53,   33,   33,   43,   53,   39,   33,   34,   34,
      394,   34,   34,   39,   34,   43,   34,   34,   34,   34,
       34,   34,   34,   41,   45,   41,   42,   34,   36,   36,
       42,   36,   36,   44,   80,   44,   36,   80,   47,   45,
       47,   42,   49,   51,   49,   73,   50,   48,   50,   48,

       54,  392,   36,   46,   54,   51,   46,   73,   48,   46,
       46,   46,   46,   46,   46,   48,   50,   55,   49,   65,
       79,   65,   50,   83,  156,   83,   55,   63,  156,   79,
       63,   79,  390,   63,   63,   63,   63,   63,   63,   64,
       64,   67,   64,   67,   89,   64,   64,   64,   64,   64,
       64,   89,   67,   84,  183,   90,   84,   90,  183,   84,
       84,   84,   84,   84,   84,   88,   91,   91,   92,   84,
       88,   93,   95,   94,   95,   92,   94,   96,   97,   96,
      107,   93,   98,   93,   99,   98,  102,  100,  141,   97,
      100,  102,  107,   99,  104,   99,  104,  104,   99,  105,

      141,  105,  105,  109,  115,  109,  115,  117,  389,  117,
      105,  114,  144,  137,  114,  137,  388,  114,  114,  114,
      114,  114,  114,  116,  144,  116,  116,  118,  116,  118,
      387,  116,  116,  116,  116,  116,  116,  140,  142,  140,
      143,  142,  143,  147,  146,  145,  148,  151,  386,  147,
      118,  138,  145,  148,  138,  146,  151,  138,  138,  138,
      138,  138,  138,  149,  152,  153,  154,  155,  149,  157,
      160,  152,  171,  385,  171,  160,  157,  154,  192,  155,
      153,  158,  384,  166,  158,  166,  166,  158,  158,  158,
      158,  158,  158,  169,  191,  191,  169,  193,  192,  169,

      169,  169,  169,  169,  169,  194,  196,  196,  193,  198,
      194,  199,  205,  202,  199,  202,  198,  204,  207,  206,
      210,  204,  206,  205,  208,  207,  211,  383,  204,  208,
      213,  210,  213,  221,  222,  221,  222,  245,  211,  212,
      241,  241,  212,  246,  245,  212,  212,  212,  212,  212,
      212,  223,  244,  246,  223,  244,  251,  223,  223,  223,
      223,  223,  223,  247,  249,  253,  247,  255,  251,  257,
      249,  257,  257,  266,  280,  266,  279,  279,  281,  282,
      281,  284,  286,  287,  280,  296,  308,  296,  308,  253,
      309,  255,  330,  382,  282,  310,  319,  309,  319,  381,

      378,  377,  376,  330,  375,  284,  286,  287,  310,  398,
      398,  374,  372,  370,  368,  367,  365,  363,  362,  361,
      360,  359,  358,  357,  356,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      338,  337,  336,  335,  334,  333,  332,  331,  329,  328,
      327,  326,  325,  324,  323,  322,  318,  316,  315,  314,
      313,  312,  311,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  297,  295,  294,  293,  292,  291,  290,  289,
      288,  285,  283,  278,  277,  276,  275,  273,  271,  270,
      269,  268,  267,  265,  264,  263,  262,  261,  260,  259,

      258,  256,  254,  252,  250,  248,  243,  242,  240,  239,
      238,  236,  234,  233,  232,  231,  230,  229,  226,  225,
      224,  220,  219,  218,  217,  216,  215,  214,  209,  203,
      201,  200,  197,  195,  190,  189,  187,  186,  185,  184,
      181,  179,  178,  177,  175,  173,  172,  170,  168,  167,
      165,  164,  163,  162,  161,  159,  139,  136,  135,  134,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  119,  113,  112,  111,  110,  108,
      106,  103,  101,   87,   86,   85,   82,   78,   77,   76,
       75,   74,   72,   71,   70,   69,   68,   66,   62,   61,

       58,   57,   56,   52,   31,   30,   29,   26,   25,   23,
       22,   18,   14,   13,   11,    9,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  397,  397,  397,  397,  397,
      397,  397,  397,  397,  397
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int sfyy_flex_debug;
int sfyy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *sfyytext;
#line 1 "server6_token.l"
/*	$Id: server6_token.l,v 1.1.1.1 2006/12/04 00:45:34 Exp $	*/
/*
 * Copyright (C) International Business Machines  Corp., 2003
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
/* Author: Shirley Ma, xma@us.ibm.com */
#line 37 "server6_token.l"
#include <stdio.h>
#include <string.h>
#include <syslog.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <net/if.h>

#include "queue.h"
#include "dhcp6.h"
#include "config.h"
#include "common.h"
#include <server6_conf.h>
#include "sf.tab.h"

int num_lines = 1;
int sfyyerrorcount = 0;
int sfparse(char *filename);
extern void sfyyerror(char *msg);
extern struct rootgroup *globalgroup;

extern int sfyyparse(void);




#line 827 "lex.sfyy.c"

#define INITIAL 0
#define S_IFACE 1
#define S_DUID 2
#define S_OPTION 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int sfyylex_destroy (void );

int sfyyget_debug (void );

void sfyyset_debug (int debug_flag  );

YY_EXTRA_TYPE sfyyget_extra (void );

void sfyyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *sfyyget_in (void );

void sfyyset_in  (FILE * in_str  );

FILE *sfyyget_out (void );

void sfyyset_out  (FILE * out_str  );

yy_size_t sfyyget_leng (void );

char *sfyyget_text (void );

int sfyyget_lineno (void );

void sfyyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int sfyywrap (void );
#else
extern int sfyywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( sfyytext, sfyyleng, 1, sfyyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( sfyyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( sfyyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, sfyyin))==0 && ferror(sfyyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(sfyyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int sfyylex (void);

#define YY_DECL int sfyylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after sfyytext and sfyyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! sfyyin )
			sfyyin = stdin;

		if ( ! sfyyout )
			sfyyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			sfyyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				sfyy_create_buffer(sfyyin,YY_BUF_SIZE );
		}

		sfyy_load_buffer_state( );
		}

	{
#line 83 "server6_token.l"


#line 1042 "lex.sfyy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of sfyytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 398 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 717 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 85 "server6_token.l"
{ return GROUP; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 87 "server6_token.l"
{ BEGIN S_IFACE; return INTERFACE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 88 "server6_token.l"
{ BEGIN INITIAL; sfyylval.str = strdup(sfyytext); return IFNAME;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 90 "server6_token.l"
{ return LINK; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "server6_token.l"
{ return RELAY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "server6_token.l"
{ return HOST; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 94 "server6_token.l"
{ return POOL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "server6_token.l"
{ return RANGE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 97 "server6_token.l"
{ return IAID; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 98 "server6_token.l"
{ return IAIDINFO; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "server6_token.l"
{ BEGIN S_DUID; return DUID; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "server6_token.l"
{ BEGIN INITIAL; sfyylval.str = strdup(sfyytext); return DUID_ID; } 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 103 "server6_token.l"
{ return PREFIX; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 104 "server6_token.l"
{ return ADDRESS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "server6_token.l"
{ BEGIN S_OPTION; return ALLOW; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 107 "server6_token.l"
{ BEGIN S_OPTION; return SEND; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 108 "server6_token.l"
{ BEGIN S_OPTION; return OPTION; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 110 "server6_token.l"
{ BEGIN INITIAL; return UNICAST; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 111 "server6_token.l"
{ BEGIN INITIAL; return RAPIDCOMMIT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 112 "server6_token.l"
{ BEGIN INITIAL; return TEMPIPV6ADDR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 113 "server6_token.l"
{ BEGIN INITIAL; return INFO_ONLY; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 114 "server6_token.l"
{ BEGIN INITIAL; return DNS_SERVERS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "server6_token.l"
{ BEGIN INITIAL; return SIP_SERVERS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "server6_token.l"
{ BEGIN INITIAL; return NTP_SERVERS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 118 "server6_token.l"
{ return RENEWTIME; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 119 "server6_token.l"
{ return REBINDTIME; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 120 "server6_token.l"
{ return VALIDLIFETIME; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 121 "server6_token.l"
{ return PREFERLIFETIME; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 122 "server6_token.l"
{ return PREFERENCE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 124 "server6_token.l"
{ return TO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 125 "server6_token.l"
{ return INFINITY; }
	YY_BREAK
case 32:
*yy_cp = (yy_hold_char); /* undo effects of setting up sfyytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up sfyytext again */
YY_RULE_SETUP
#line 127 "server6_token.l"
{/* ignore comments */}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 128 "server6_token.l"
{num_lines++;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "server6_token.l"
{}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "server6_token.l"
{
			struct in6_addr addr;
			int i;
				
			i = inet_pton(AF_INET6, sfyytext, &addr);
			if (i < 1) {
				dprintf(LOG_ERR, "invalid address in line %d", num_lines); 
				return BAD_TOKEN;
			}

			sfyylval.addr = addr;
			return IPV6ADDR;
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 144 "server6_token.l"
{ sfyylval.num = strtoll(sfyytext, NULL, 10); return NUMBER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 145 "server6_token.l"
{ sfyylval.snum = strtoll(sfyytext, NULL, 10); return SIGNEDNUMBER; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 146 "server6_token.l"
{ sfyylval.dec = atof(sfyytext); return DECIMAL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 147 "server6_token.l"
{
			static char name[MAXDNAME];
			strncpy(name, sfyytext, MAXDNAME-1);
			name[MAXDNAME-1] = '\0';
			sfyylval.str = name;
			return STRING;
		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 154 "server6_token.l"
{ return *sfyytext; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 155 "server6_token.l"
{ return BAD_TOKEN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 157 "server6_token.l"
ECHO;
	YY_BREAK
#line 1331 "lex.sfyy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_IFACE):
case YY_STATE_EOF(S_DUID):
case YY_STATE_EOF(S_OPTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed sfyyin at a new source and called
			 * sfyylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = sfyyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( sfyywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * sfyytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of sfyylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					sfyyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			sfyyrestart(sfyyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) sfyyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 398 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 398 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 397);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up sfyytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					sfyyrestart(sfyyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( sfyywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve sfyytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void sfyyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        sfyyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            sfyy_create_buffer(sfyyin,YY_BUF_SIZE );
	}

	sfyy_init_buffer(YY_CURRENT_BUFFER,input_file );
	sfyy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void sfyy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		sfyypop_buffer_state();
	 *		sfyypush_buffer_state(new_buffer);
     */
	sfyyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	sfyy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (sfyywrap()) processing, but the only time this flag
	 * is looked at is after sfyywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void sfyy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	sfyyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE sfyy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) sfyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in sfyy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) sfyyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in sfyy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	sfyy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with sfyy_create_buffer()
 * 
 */
    void sfyy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		sfyyfree((void *) b->yy_ch_buf  );

	sfyyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a sfyyrestart() or at EOF.
 */
    static void sfyy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	sfyy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then sfyy_init_buffer was _probably_
     * called from sfyyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void sfyy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		sfyy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void sfyypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	sfyyensure_buffer_stack();

	/* This block is copied from sfyy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from sfyy_switch_to_buffer. */
	sfyy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void sfyypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	sfyy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		sfyy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void sfyyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)sfyyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in sfyyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)sfyyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in sfyyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE sfyy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) sfyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in sfyy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	sfyy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to sfyylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       sfyy_scan_bytes() instead.
 */
YY_BUFFER_STATE sfyy_scan_string (yyconst char * yystr )
{
    
	return sfyy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to sfyylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE sfyy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) sfyyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in sfyy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = sfyy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in sfyy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up sfyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		sfyytext[sfyyleng] = (yy_hold_char); \
		(yy_c_buf_p) = sfyytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		sfyyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int sfyyget_lineno  (void)
{
        
    return sfyylineno;
}

/** Get the input stream.
 * 
 */
FILE *sfyyget_in  (void)
{
        return sfyyin;
}

/** Get the output stream.
 * 
 */
FILE *sfyyget_out  (void)
{
        return sfyyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t sfyyget_leng  (void)
{
        return sfyyleng;
}

/** Get the current token.
 * 
 */

char *sfyyget_text  (void)
{
        return sfyytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void sfyyset_lineno (int  line_number )
{
    
    sfyylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see sfyy_switch_to_buffer
 */
void sfyyset_in (FILE *  in_str )
{
        sfyyin = in_str ;
}

void sfyyset_out (FILE *  out_str )
{
        sfyyout = out_str ;
}

int sfyyget_debug  (void)
{
        return sfyy_flex_debug;
}

void sfyyset_debug (int  bdebug )
{
        sfyy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from sfyylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    sfyyin = stdin;
    sfyyout = stdout;
#else
    sfyyin = (FILE *) 0;
    sfyyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * sfyylex_init()
     */
    return 0;
}

/* sfyylex_destroy is for both reentrant and non-reentrant scanners. */
int sfyylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		sfyy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		sfyypop_buffer_state();
	}

	/* Destroy the stack itself. */
	sfyyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * sfyylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *sfyyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *sfyyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void sfyyfree (void * ptr )
{
	free( (char *) ptr );	/* see sfyyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 157 "server6_token.l"



int
sfparse(conf)
        char *conf;
{
        if ((sfyyin = fopen(conf, "r")) == NULL) {
                if (errno == ENOENT)
                        return(0);
                dprintf(LOG_ERR, "sfparse: fopen(%s): %s",
                        conf, strerror(errno));
		printf("open error\n");
                return(-1);
        }

        if (sfyyparse() || sfyyerrorcount) {
                sfyyerror("fatal parse failure: exiting");
                return(-1);
        }
	post_config(globalgroup);

	return (0);
}

