# $ld$

include ../config.in
include ../config.mk



BIN  := dlnad

all: 



install: 
	install -d $(TARGETDIR)/usr/sbin
	install -m 755 $(BIN) $(TARGETDIR)/usr/sbin
	$(STRIP) $(TARGETDIR)/usr/sbin/$(BIN)

clean:


