include ../config.in
include ../config.mk


STRIPCMD := $(STRIP) --strip-all --remove-section=.note --remove-section=.comment --remove-section=.pdr

TARGET = check_fw 

all: 


clean:

	
install: 
	install -d $(TARGETDIR)/usr/sbin
	install check_fw $(TARGETDIR)/usr/sbin


