#
# Ambit web pages
#
# Copyright 2005, Foxconn Corporation
# All Rights Reserved.
# 
# THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
# KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
# SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
#
# $Id$
#

include ../config.mk
include ../config.in
WWWROOT_PATH=www

all: packfiles.cfg

PAGES := form.css help.css
PAGES += browser.js func.js msg.js utility.js
ifeq ($(PROFILE),WNR2200)
PAGES += settings_wnr2200.jpg mimo_logo.jpg
STR_TBL_FILE=string_table_wnr2200
endif

ifeq ($(PROFILE),WN2000RPTv2)
PAGES += settings_wnr2200.jpg mimo_logo.jpg
STR_TBL_FILE=string_table_wnr2200
endif

ifeq ($(PROFILE),WNR2100)
PAGES += settings_wnr2100.jpg mimo_logo.jpg
STR_TBL_FILE=string_table_wnr2100
endif

ifeq ($(PROFILE),WGR614v10)
ifeq ($(FW_TYPE),BRIC)
PAGES += settings_wgr614v10bric.jpg mimo_logo_wgr614v10bric.jpg
STR_TBL_FILE=string_table_wgr614v10bric
else
PAGES += settings_wgr614v10.jpg mimo_logo_wgr614v10.jpg
STR_TBL_FILE=string_table_wgr614v10
endif
endif

ifeq ($(PROFILE),WNR1000v3)
PAGES += settings_wnr1000v3.jpg mimo_logo_wnr1000v3.jpg
STR_TBL_FILE=string_table_wnr1000v3
endif

ifeq ($(PROFILE),WNDR3400)
#PAGES += settings_wndr3400.jpg mimo_logo_wndr3400.jpg
PAGES += settings_wndr3400v2.jpg mimo_logo_wndr3400.jpg
STR_TBL_FILE=string_table_wndr3400
endif

ifeq ($(PROFILE),WNDR3400v3)
#PAGES += settings_wndr3400.jpg mimo_logo_wndr3400.jpg
PAGES += settings_wndr3400v3.jpg mimo_logo_wndr3400.jpg
STR_TBL_FILE=string_table_wndr3400v3
endif
ifeq ($(PROFILE),WNDR4500REV)
PAGES += settings_wndr4500rev.jpg mimo_logo_wndr4500rev.jpg
STR_TBL_FILE=string_table_wndr4500rev
endif


ifeq ($(PROFILE),WNDR3400AC)
PAGES += settings_wndr3400ac.jpg mimo_logo_wndr3400ac.jpg
STR_TBL_FILE=string_table_WNDR3400AC
endif


ifeq ($(PROFILE),R6300v2)
PAGES += settings_r6300_v2.jpg mimo_logo_r6300v2.jpg
STR_TBL_FILE=string_table_r6300v2
endif

ifeq ($(PROFILE),R7000)
PAGES += settings_r7000.jpg mimo_logo_r7000.jpg 
IMG_PAGES += img/remote_app.jpg
STR_TBL_FILE=string_table_r7000
endif

ifeq ($(PROFILE),AC1450)
PAGES += settings_ac1450.jpg mimo_logo_ac1450.jpg
STR_TBL_FILE=string_table_ac1450
endif

ifeq ($(PROFILE),R6250)
PAGES += settings_r6250.jpg mimo_logo_r6250.jpg
STR_TBL_FILE=string_table_r6250
endif

ifeq ($(PROFILE),R6200v2)
PAGES += settings_r6200v2.jpg mimo_logo_r6200v2.jpg
STR_TBL_FILE=string_table_r6200v2
endif

ifeq ($(PROFILE),WNDR4500v2)
PAGES += settings_wndr4500v2.jpg mimo_logo_wndr4500rev.jpg
STR_TBL_FILE=string_table_wndr4500v2
endif

ifeq ($(PROFILE),R4500)
PAGES += settings_R4500.jpg mimo_logo_wndr4500rev.jpg
STR_TBL_FILE=string_table_R4500
endif

ifeq ($(PROFILE),WNDR3300v2)
PAGES += settings_wndr3300v2.jpg mimo_logo_wndr3300v2.jpg
STR_TBL_FILE=string_table_wndr3300v2
endif

ifeq ($(PROFILE),WNR2000v2)
PAGES += settings_wnr2000v2.jpg
STR_TBL_FILE=string_table_wnr2000v2
endif

ifeq ($(PROFILE),WNR3500U)
STR_TBL_FILE=string_table_wnr3500u
PAGES += settings_wnr3500u.bmp
endif

ifeq ($(PROFILE),WNR3500L)
ifeq ($(FW_TYPE),RU)
STR_TBL_FILE=string_table_wnr3500l_RU
else
STR_TBL_FILE=string_table_wnr3500l
endif
PAGES += settings_wnr3500l.jpg
PAGES += mimo_logo_wnr3500.jpg
endif

ifeq ($(PROFILE),WNR3500Lv2)
STR_TBL_FILE=string_table_wnr3500lv2
PAGES += settings_wnr3500lv2.jpg
PAGES += mimo_logo_wnr3500.jpg
endif

ifeq ($(PROFILE),WNDR3700v3)
STR_TBL_FILE=string_table_wndr3700v3
PAGES += settings_wndr3700v3.jpg
PAGES += mimo_logo_wndr4500.jpg
endif
ifeq ($(PROFILE),WNDR4500)
STR_TBL_FILE=string_table_wndr4500
ifeq ($(CONFIG_RU_WAN_FLOW),y)
STR_TBL_FILE=string_table_wndr4500_ru
else
STR_TBL_FILE=string_table_wndr4500
endif
PAGES += settings_wndr4500.jpg
PAGES += mimo_logo_wndr4500.jpg
endif





PAGES += settings_d6400.jpg mimo_logo_d6300v2.jpg
STR_TBL_FILE=string_table_D7000v2
PAGES += genie_dyn_option.htm genie_dyn_option2.htm genie_adv_adsl.htm genie_adv_vdsl.htm
PAGES += LED_settings.htm
IMG_PAGES += img/AP_Mode-D7000v2.JPG
PAGES += DSL_PRO_config.html
PAGES += burnsku.htm


PAGES += WLG_wireless_dual_band_r10.htm


PAGES += upnp.ico

PAGES += darkblue.gif liteblue.gif menublue.gif redbull.gif spacer.gif upload_new.gif
PAGES += index.htm start.htm GPL_rev1.htm
PAGES += BAK_backup.htm BAK_backup_h.htm BAK_cfm.htm
PAGES += BAS_basic.htm BAS_basictop.htm BAS_wtest_d.htm BAS_wtest_l.htm
PAGES += BAS_ether.htm BAS_ether_h.htm
PAGES += BAS_pppoe.htm BAS_pppoe_h.htm
PAGES += BAS_pptp.htm BAS_pptp_h.htm
PAGES += BAS_bpa_h.htm
PAGES += BKS_keyword.htm BKS_keyword_h.htm
PAGES += BKS_service.htm BKS_service_h.htm
PAGES += BKS_service_add.htm BKS_service_add_h.htm
PAGES += BKS_service_edit.htm BKS_err.htm
#PAGES += BAS_bpa.htm RST_st_bpa.htm

PAGES += DEV_device.htm
PAGES += DDNS_Yes.png
PAGES += DDNS_No.png
PAGES += DDNS_NoIplog.png
PAGES += DNS_ddns_Netgear_yes_h.htm
PAGES += DNS_ddns_Netgear_no_h.htm
PAGES += DEV_device_h.htm
PAGES += DEV_control.htm DEV_control_h.htm DEV_device2.htm DEV_device2_h.htm DEV_access_block.htm DEV_control_add.htm
PAGES += DEV_control_edit.htm
PAGES += WEB_site_block.htm 
PAGES += DNS_ddns.htm DNS_ddns_h.htm DNS_ddns_st.htm
ifeq ($(CONFIG_OPENVPN),y)
PAGES += OPENVPN.htm OPENVPN_hidden.htm openvpn_help.htm
endif
PAGES += DIG_reboot.htm DIG_reboot2.htm
PAGES += FW_email.htm FW_email_h.htm


PAGES += FW_forward_h.htm FW_forward_service_h.htm
ifeq ($(NEW_FORWARD_SPEC),y)
ifeq ($(CONFIG_BRIC_SPEC_SUPPORT),y)
PAGES += FW_forward3.htm FW_forward_service3.htm
else
PAGES += FW_forward2.htm FW_forward_service2.htm
endif
else
PAGES += FW_forward.htm  FW_forward_service.htm
endif
PAGES += FW_log.htm FW_log_h.htm
PAGES += FW_remote.htm FW_remote_h.htm
PAGES += FW_schedule.htm FW_schedule_h.htm
PAGES += LAN_lan.htm LAN_lan_h.htm LAN_reserv_add.htm LAN_reserv_add_h.htm LAN_reserv_edit.htm LAN_reserv_edit_h.htm
PAGES += LGO_logout.htm
PAGES += MNU_menu.htm MNU_top.htm MNU_login.htm MNU_blank.htm MNU_access_failure.htm MNU_access_unauthorized.htm
PAGES += PWD_password.htm PWD_passwd_h.htm

PAGES += RST_status.htm RST_status_h.htm RST_statistics.htm RST_stattbl.htm RST_interval.htm RST_wanstat.htm RST_st_dhcp.htm RST_st_poe.htm RST_st_fix.htm RST_st_pptp.htm
PAGES += RST_st_ppa.htm
PAGES += RST_st_ipoa.htm

PAGES += SRV_response.htm
PAGES += STR_routes.htm STR_routes_h.htm STR_add.htm
PAGES += UPG_upgrade.htm UPG_upgrade_h.htm UPG_upgrade_ver_check.htm
PAGES += UPNP_upnp.htm UPNP_upnp_h.htm
PAGES += WAN_wan.htm WAN_wan_h.htm

PAGES += WIZ_sel.htm WIZ_sel_h.htm WIZ_sel2.htm WIZ_cfm.htm WIZ_cfm_h.htm WIZ_detwan.htm WIZ_result.htm WIZ_det_fix.htm WIZ_det_fix_h.htm WIZ_dyn.htm WIZ_dyn_h.htm WIZ_fix.htm WIZ_fix_h.htm WIZ_pppoe.htm WIZ_pppoe_h.htm WIZ_ph_fail.htm WIZ_ph_fail_h.htm WIZ_bpa.htm WIZ_bpa_h.htm
PAGES += WLG_wireless.htm WLG_wireless1.htm WLG_wireless2.htm WLG_wireless3.htm WLG_wireless_h.htm WLG_adv.htm WLG_adv_h.htm

PAGES += wep.js
PAGES += WLG_wifi_sche_set.htm WLG_wifi_sche_set_warn.htm WLG_adv_sche_set_h.htm WLG_wifi_sche_set_h.htm
PAGES += WLG_ap_dual_band.htm WLG_ap_dual_band_h.htm






PAGES += WLG_wireless_dual_band.htm WLG_adv_dual_band.htm WLG_wireless_dual_band_2.htm WLG_2g_wireless1_2.htm WLG_2g_wireless2_2.htm WLG_2g_wireless3_2.htm WLG_5g_wireless1_2.htm WLG_5g_wireless2_2.htm WLG_5g_wireless3_2.htm

PAGES += md5.js
PAGES += WLG_acl.htm WLG_acl_h.htm
PAGES += WLG_acl_add.htm WLG_acl_add_h.htm
PAGES += WLG_acl_edit.htm


PAGES += BAS_dsl.htm BAS_dsl_h.htm IPV6_pppoa.htm IPV6_pppoa_h.htm BAS_pppoa.htm BAS_pppoa_h.htm

PAGES += FW_pt.htm FW_pt_h.htm FW_pt_service.htm
PAGES += WIZ_pptp.htm WIZ_pptp_h.htm

PAGES += FW_check.htm
PAGES += style.css 

ifeq ($(UPNP_ENABLE_FLAG),y)
PAGES += Public_UPNP_gatedesc.xml Public_UPNP_WANIPConn.xml Public_UPNP_WAND.xml Public_UPNP_Layer3F.xml
endif
ifeq ($(INTERNET_UPGRADE_FLAG),y)
PAGES += VER_check.htm VER_check_h.htm VER_download.htm VER_download_h.htm VER_fw_found.htm VER_fw_not_found.htm VER_result_h.htm VER_sel.htm VER_sel_h.htm VER_write.htm VER_write_h.htm VER_write2.htm
endif
ifeq ($(POT_ENABLE_FLAG),y)
PAGES +=  POT.htm
endif
PAGES += DIAG_diag.htm DIAG_diag_h.htm DIAG_ping.htm DIAG_rt.htm DIG_reboot3.htm
ifeq ($(WAN_LAN_CONFLICT_ENABLE_FLAG),y)
PAGES +=  important_update.htm IA_IP_SUBNET.htm start_update.htm DIG_reboot4.htm
endif
PAGES += Public_UPNP_WANEtherLinkCfg.xml Public_UPNP_WANPPPConn.xml Public_UPNP_LANHostCfgMag.xml
PAGES += router-info.htm
# wklin added, 11/23/2006, for vista wcn and build-in registar
# PAGES += VST_vista.htm VST_vista_h.htm VST_add_client.htm VST_wps_status.htm
PAGES += UPG_fw_check.htm
PAGES += CheckNewFW.html NoInternetConn.html currentsetting.htm
PAGES += QOS_main.htm QOS_main_h.htm QOS_service.htm QOS_ruletab.htm QOS_check_uplink_band_width.htm NoInternet.html
PAGES += poweredbyookla.png
#QOS_main_no_bw.htm QOS_bw.htm
ifeq ($(TRAFFIC_METER_FLAG),y)
PAGES +=  traffic_important_update.htm traffic_interval.htm traffic_meter.htm traffic_meter_h.htm
PAGES +=  traffic_start_update.htm traffic_stattbl.htm traffic_status.htm traffic_warning.htm
endif

#water added, 11/05/2008, usb pages
ifeq ($(SAMBA_ENABLE_FLAG),y)
PAGES += USB_basic.htm USB_basic_h.htm
PAGES += USB_adv.htm USB_adv_h.htm USB_adv_add.htm USB_adv_edit.htm USB_basic_main.htm USB_adv_main.htm USB_basic_printing.htm USB_basic_vault.htm
PAGES += Adv_USB.htm Adv_USB_h.htm USB_basic_remote.htm USB_basic_remote_h.htm USB_basic_remote_reg.htm USB_basic_remote_unreg.htm
PAGES += base.gif dtree.css dtree.js empty.gif folder.gif folderopen.gif
PAGES += imgfolder.gif join.gif joinbottom.gif line.gif minus.gif minusbottom.gif page.gif
PAGES += plus.gif plusbottom.gif sda.gif trash.gif
PAGES += USB_folderBrowse.htm
PAGES += USB_umount.htm
PAGES += USB_settings.htm USB_settings_h.htm
PAGES += WLG_wireless_2_h.htm
endif

PAGES += genie_ping_ap_mode.htm Congratulations_ap_mode.htm Congratulations2_ap_mode.htm genie_ap_mode_start.htm genie_ap_mode_check.htm genie_ap_result.htm genie_ap_dual_band.htm genie_ap_mode_apply.htm changeUrl.js
#foxconn Tab Tseng add start, 03/31/2014, CDL genie software download flow
PAGES += genie_download_href.htm genie_download_wait.htm genie_download.htm genie_download_skip.htm
IMG_PAGES += img/wait.gif img/genie_download.jpg

# WPS pages from Netgear
PAGES += Add_WPS_Client.htm WPS_h.htm
PAGES += WPS.htm WPS_PIN.htm
#PAGES += WPS.htm WPS_Add_Client.htm
# WPS_Client_PIN.htm 
PAGES += WPS_Add_Client_FAIL_Cancel.htm WPS_Add_Client_FAIL_PIN_Change.htm 
PAGES += WPS_Add_Client_FAIL_Timeout.htm
PAGES += WPS_Add_Client_OK.htm
PAGES += WPS_Add_Client_FAIL_Cancel_Change.htm
PAGES += WPS_Add_Client_FAIL_Timeout_Change.htm
PAGES += WPS_Add_Client_FAIL_PIN.htm
# PAGES += WPS_Add_Client_PIN_Change.htm
PAGES += WPS_Add_Client_FAIL_PBC_Conflict.htm
PAGES += WPS_Add_Client_FAIL_PBC_Conflict_Change.htm
PAGES += WPS_Add_Client_PBC.htm
PAGES += WPS_Add_Client_PIN.htm
PAGES += WPS_Add_Client_OK_Change.htm
PAGES += wps_icon_on.bmp wps_icon_off.bmp
PAGES += MNU_menu_no_link.htm
PAGES += WiFi_HiddenPage.htm
PAGES += WPS_Add_Client_FAIL_ErrorPIN.htm

PAGES += debuginfo.htm
ifeq ($(CONFIG_HIDDEN_PAGE_DEBUG),y)
PAGES += DebugHiddenPage.htm
ifeq ($(CONFIG_NEW_DEBUG_HIDDEN_PAGE),y)
PAGES += debug.htm
endif
endif
PAGES += jquery.js BAS_pppoe_basic.htm BAS_pppoe_basictop.htm 

PAGES += BAS_pppoe_flet.htm BAS_pppoe_flet2.htm BAS_pppoe_other.htm WIZ_pppoe_fleteast.htm WIZ_pppoe_fletother.htm WIZ_pppoe_fletwest.htm


ifeq ($(MULTI_LANG_ENABLE),y)
PAGES += LANG_lang.htm LANG_lang_h.htm LANG_check.htm LANG_no_connection.htm LANG_brs_conflict_h.htm StringTableUpload.html backpage.htm backpage2.htm VER_fwlang_found.htm
PAGES += LANG_found.htm LANG_not_found.htm LANG_download.htm LANG_write.htm  LANG_check_top.htm LANG_check_brslang.htm LANG_brs_conflict.htm LANG_failed.htm LANG_upgrade.htm
endif
#foxconn added start, water, 12/21/09, @restart all process
PAGES += DIG_update.htm
#foxconn added end, water, 12/21/09
ifeq ($(L2TP_ENABLE_FLAG),y)
PAGES += BAS_l2tp.htm BAS_l2tp_h.htm RST_st_l2tp.htm
endif

ifeq ($(CONFIG_REPEATER_MODE),y)
PAGES += st_top.htm ca.jpg router.jpg router_link_off.jpg router_link_green.jpg repeater_green.jpg client_link_off.jpg client.jpg 
PAGES += IA_AP_settings.htm IA_change_lang.htm IA_led.htm IA_manual_ssid.htm IA_menu.htm IA_scan_result.htm wizard_to_welcome.html IA_WEP.htm IA_WPA.htm IA_welcome.htm
PAGES += WZC.jpg IA_review_setting.htm IA_index.htm IA_finish.htm IA_frame.htm
PAGES += repeater.js
endif

ifeq ($(INCLUDE_IPV6_FLAG),y)
PAGES += IPV6_auto.htm IPV6_basic.htm IPV6_basictop.htm IPV6_dhcp.htm IPV6_disable.htm IPV6_fixed.htm IPV6_passthrough.htm IPV6_pppoe.htm IPV6_tunnel.htm IPV6_autoconfig.htm
PAGES += IPV6_h.htm IPV6_auto_h.htm IPV6_dhcp_h.htm IPV6_fixed_h.htm IPV6_pppoe_h.htm IPV6_tunnel_h.htm IPV6_autoconfig_h.htm IPV6_basictop1.htm
PAGES += IPV6_6rd.htm
endif
ifeq ($(ENABLE_VPN),y)
PAGES += utility1.js linux1.js
#Foxconn add, Pingod.Ping 11/17/2007
PAGES += VPN_wizard.htm VPN_wizard_h.htm
PAGES += VPN_status.htm VPN_status_h.htm
PAGES += VPN_policies.htm VPN_policies_h.htm
PAGES += VPN_wizard_setup1.htm
PAGES += VPN_wizard_setup2.htm
PAGES += VPN_wizard_setup3.htm
PAGES += VPN_wizard_setup4.htm
PAGES += VPN_Auto_policy.htm VPN_Auto_policy_h.htm
PAGES += VPN_Manual_policy.htm VPN_Manual_policy_h.htm
PAGES += VPN_Consortium.htm
PAGES += DIG_update_vpn.htm
#Foxconn add, WaterQiu 11/19/2007
PAGES += VPN_sta.htm 
endif

PAGES += selects_disabled.gif selects.gif
PAGES += MNU_top_hide.htm CheckNewFirmware.htm close_process.htm

# Foxconn added by Kathy, 10/14/2013 for wifi facebook
ifeq ($(INCLUDE_FBWIFI_FLAG),y)
PAGES += fbwifi.htm fbwifi_h.htm
endif

#CDLess flag start,added by dennis ,01/11/2011, @cdless porting
# new gui and genie  added by dennis start , 2010/10/18
PAGES += genie_start.htm genie_result.htm genie_ph_fail.htm Congratulations.htm Congratulations2.htm genie_pppoe.htm genie_dyn.htm genie_pppoa.htm \
genie_restore.htm genie_fix.htm genie_ipoa.htm genie_pptp.htm genie_bpa.htm genie_redirect.htm DEV_redirect.htm  UPG_fw_check2.htm
PAGES += genie_apply.htm genie_restoring.htm  genie_detwan.htm genie_ether.htm genie_no_con.htm genie_down.htm \
genie_otherissue.htm genie_ping.htm genie_redirect_successpage.htm genie_redirect_successpage2.htm genie_detecting.htm genie_redirect_successpage3.htm
PAGES += genie_check_brslang.htm genie_ping2.htm genie_ping3.htm genie_pppoe2.htm genie_pppoa2.htm genie_IP_SUBNET.htm genie_IP_SUBNET2.htm
PAGES += genie_basic.htm DashBoard.htm ajax-loader.gif genie_pptp2.htm genie_bpa2.htm jquery.alerts.css jquery.alerts.js
PAGES += genie_select_country.htm
PAGES += genie_det_line.htm genie_line_down.htm

CSS_PAGES = css/mainpage.css  css/menu.css  css/standalone.css  css/table.css css/table_noh.css css/tabs.css css/button.css css/scrollbar.css css/help.css css/jquery.jscrollpane.css css/MNUAccess.css css/jquery.flexbox.css
SCRIPT_PAGES = script/script.js  script/sorttable.js script/jquery.jscrollpane.min.js script/jquery.mousewheel.js script/jquery.flexbox.min.js

PAGES += genie_strtab_English genie_strtab_Chinese genie_strtab_Russian genie_strtab_Arabic genie_strtab_Bulgarian genie_strtab_Croatian genie_strtab_Czech \
genie_strtab_Danish genie_strtab_Dutch genie_strtab_Finnish genie_strtab_French genie_strtab_German genie_strtab_Greek genie_strtab_Hungarian genie_strtab_Italian \
genie_strtab_Korean genie_strtab_Norwegian genie_strtab_Polish genie_strtab_Portuguese genie_strtab_Romanian genie_strtab_Slovak \
genie_strtab_Slovenian genie_strtab_Spanish genie_strtab_Swedish genie_strtab_Japanese

PAGES += auto_block.htm
# new gui and genie  added by dennis end , 2010/10/18
#CDLess flag end
ifeq ($(CONFIG_ADMIN_ACCOUNT), y)
PAGES += genie_admin_account.htm genie_admin_account2.htm 
endif

ifeq ($(VLAN_SUPPORT), y)
PAGES += VLAN_IPTV.htm VLAN_IPTV_h.htm VLAN_IPTV_add.htm VLAN_IPTV_edit.htm
endif
# Foxconn Perry added start, 2010/11/22, for password recovery
PAGES += MNU_accessUnauthorized_checkAnswer.htm MNU_access_unauthorized_checkSerial.htm 
PAGES += MNU_accessPasswdRecovery.htm MNU_accessUnauthorized_checkAnswerAgain.htm
PAGES += MNU_accessUnauthorized_checkSerialAgain.htm MNU_access_close_page.htm
PAGES += MNU_accessPassword_recovered.htm MNU_access_login.htm MNU_access_login2.htm
PAGES += MNU_access_login_top.htm MNU_access_login_frame.htm  MNU_access_multiLogin2.htm
PAGES += MNU_access_setRecovery_index.htm MNU_access_setRecovery_redirect.htm
# Foxconn removed by Kathy, 04/13/2016 @ fixed security issue
#PAGES += MNU_access_unauthorized_redirect.htm MNU_access_unauthorized_index.htm 
# Foxconn Perry added end, 2010/11/22, for password recovery

PAGES += dlna.htm
# Foxconn Perry added start, 2010/12/08, for help scrollbar
SCRIPT_PAGES += script/jScrollPane.js script/jScrollPane1.js
CSS_PAGES += css/jScrollPane.css
# Foxconn Perry added end, 2010/12/08, for help scrollbar

# Foxconn Perry added start, 2010/12/16, for progress bar in "Advanced Wireless Settings" page and "Guest Network" page
PAGES += DIG_reboot_wireless.htm DIG_reboot_guestNetwork.htm
# Foxconn Perry added end, 2010/12/16, for progress bar in "Advanced Wireless Settings" page "Guest Network" page

# Foxconn Perry added start, 2010/12/20, for advanced homepage
PAGES += ADVANCED_home2.htm ADVANCED_home1.htm
# Foxconn Perry added end, 2010/12/20, for advanced homepage
PAGES += g_button_sprite.gif button_sprite.gif effect.js CDL.css loading.gif loading.css Netgeargenie.png roundedcornr_input.gif chrome.css CDL2.css
PAGES += g_button_sprite_1.gif g_button_sprite_2.gif button_sprite_1.gif button_sprite_2.gif
PAGES += DashBackTop.gif DashBackCenter.gif DashBackBottom.gif DashBottom.gif DashCenter.gif DashBottomR.gif DashBottomY.gif background_gradient.jpg 
PAGES += error.png warning.png ParentalControl.jpg AttachedDevice.jpg GuestNetwork.jpg Internet.jpg
PAGES += WIZ_Gaming.htm ADVANCED_home.htm MNU_multiLogin.htm INT_statistics.htm genie_index.htm genie_top.htm frame_back.htm MNU_relogin.htm\
LANG_check_redirect.htm LANG_check_redirect2.htm  LANG_check_top2.htm backpage3.htm
IMG_PAGES += img/add_icon.gif img/roundedcornr_306126.gif img/apply_icon.gif img/barrow_down.jpg img/roundedcornr_637010.gif img/barrow.jpg img/barrow.gif img/barrow_down_nobackground.gif img/barrow_nobackground.gif\
 img/roundedcornr_802784.gif  img/roundedcornr_806183.gif img/roundleft_apply.gif img/box-header-background.gif img/roundleft_button.gif img/box-header-background-large.gif img/roundleft_update.gif img/roundright_update.gif\
 img/cancel_icon.gif img/roundright_apply.gif img/edit_icon.gif img/roundright_button.gif img/firmware-hint-background.gif  img/firmware-hint-background-long.gif img/firmware-hint-background-long-long.gif img/roundtopleft_table.gif \
img/good-icon.gif img/roundtopright_table.gif img/helparrowdown-icon.gif img/search-go.gif img/helparrowup-icon.gif img/subhead2-bottom.gif img/help-icon.gif \
img/cover-image_p.gif img/subhead2-top.gif img/subhead2-top_noh.gif img/main-page-bottom-large.gif img/main-page-bottom.gif img/subhead-bottom.gif img/Netgeargenie.png img/NewNetgeargenie.png img/subhead-top.gif img/page-table-bottom-2.gif img/subMenuActiveLarge.png img/firmware-hint-background-short.gif\
 img/page-table-bottom.gif img/subMenuActive.png img/page-table-button.gif img/page-table-button-large.gif img/page-table-button-gray.gif img/page-table-icon.gif img/page-table-seperate.gif img/tabs.gif\
 img/roundbottomleft_table.gif img/roundbottomright_table.gif img/warning-icon.gif img/roundedcornr_239763.gif img/warrow.jpg img/error.png img/error-icon.gif\
 img/warning.png img/basic-white-button.gif img/basic-purple-button.gif img/refresh-icon.gif\
 img/subhead2-background.jpg img/subhead2-background_noh.jpg img/roundright_grey.gif img/roundleft_grey.gif img/gray-button.gif img/tab-active.gif img/tab-nonactive.gif img/cover-image.gif img/cover-image_noh.gif\
 img/title.gif img/info.gif img/sel_win7.gif img/ReadyShare.gif img/Wireless.gif img/basic-purple-button-large.gif img/basic-black-button-large.gif img/basic-gray-button-large.gif \
 img/footer.gif img/footer_double.gif img/search_button.gif img/search_button_long.gif img/search_button_middle.gif img/basic-green-button.gif img/pvpn.jpg

HELP_PAGES = help/BAS_ether_h.htm help/LAN_reserv_add_h.htm

#added by Antony 101215 for DLNA
PAGES += UPNP_media_h.htm UPNP_media.htm
# added by Antony 101207 for new gui
PAGES += BAS_basictop1.htm BAS_basictop2.htm 

#Foxconn added start by Bob 10/27/2011 for wifi cert.
PAGES += wifisettings.htm
#Foxconn added end by Bob 10/27/2011 for wifi cert.

#Foxconn Perry added start, 2012/08/08, for ReadySHARE Cloud Desktop genie
USB_PAGES += cgi-bin/RMT_invite_reg.htm cgi-bin/RMT_invite_unreg.htm cgi-bin/USB_reg_success.htm cgi-bin/USB_reg_failed.htm cgi-bin/USB_unreg_success.htm
#Foxconn Perry added end, 2012/08/08, for ReadySHARE Cloud Desktop genie

#Add device mode
PAGES += Device_mode.htm Device_mode_h.htm
#Foxconn added by Kathy, 11/04/2013
ifeq ($(CONFIG_USERSETUP),y)
PAGES += User_setup.htm User_setup_add.htm User_setup_edit.htm User_setup_rename_msg.htm 
endif 
#Foxconn added by kathy 2014/02/26
PAGES += Readyshare_Storage.htm USB_adv_tab.htm
PAGES += jquery-1.8.2.js jquery.ui.core.js jquery.ui.widget.js jquery.ui.tabs.js jquery.ui.all.css jquery-ui.css jquery-ui.js jquery.ui.base.css
#Foxconn added by Kathy, 01/15/2014 @ readyDrop
#CGI_BIN += cgi-bin/delete.cgi cgi-bin/download.cgi cgi-bin/makedir.cgi cgi-bin/status.cgi cgi-bin/upload.cgi cgi-bin/upload.sh cgi-bin/file.txt
CGI_BIN += cgi-bin/readydropd.conf 
#Foxconn added by Kathy, 03/12/2014 @ xAgent_cloud 
ifeq ($(CONFIG_CLOUD_XAGENT_CONF),y)
CGI_BIN += cgi-bin/genie.cgi
PAGES += xAgent_cgi.htm XCloudLog.htm
endif
ifeq ($(CONFIG_READYCLOUD_NEW_PATH),y)
CGI_BIN += cgi-bin/readycloud_control.cgi
endif
## For CSRF page not found issue.
PAGES += csrf_timeout.htm

ifeq ($(STA_MODE),y)
PAGES += WLG_adv_dual_band2.htm RST_bridge_status.htm
ifneq ($(PROFILE),D6400)
ifneq ($(PROFILE),D6220)
ifneq ($(PROFILE),D7000v2)
ifneq ($(PROFILE),D6220v2)
PAGES += WLG_bridge_wireless_settings.htm WLG_bridge_close.htm
endif
endif
endif
endif
endif

### For D6300 system debug purpose.
PAGES += system_info.htm
#Foxconn Jenny added for IPTV page, 2013/05/15
###PAGES += litepurple.gif IPTV.htm
#Russia wizard
###PAGES += genie_iptv_detecting.htm genie_iptv_start.htm genie_iptv_fail.htm genie_iptv_success.htm

#PAGES += GPL.htm ## no for retail D6400
PAGES += WIZ_select.htm genie_det_full_pvc.htm genie_sel_full_pvc.htm

PAGES += check.jpg

ifeq ($(INCLUDE_WIZ_LOG),y)
PAGES += log.htm log2.htm
endif

PAGES += Congratulations3.htm Congratulations4.htm

ifeq ($(INCLUDE_CONSOLE_LOG),y)
PAGES += console_log.htm
endif


STR_TBL_FILE += string_table_2 string_table_3 string_table_4 string_table_5 string_table_6
STR_TBL_FILE += string_table_7 string_table_10

	
install: all
	rm -r -f $(TARGETDIR)/$(WWWROOT_PATH)
	install -d $(TARGETDIR)/$(WWWROOT_PATH)
	mkdir -p $(TARGETDIR)/$(WWWROOT_PATH)
	mkdir -p $(TARGETDIR)/$(WWWROOT_PATH)/css
	mkdir -p $(TARGETDIR)/$(WWWROOT_PATH)/img
	mkdir -p $(TARGETDIR)/$(WWWROOT_PATH)/script
	mkdir -p $(TARGETDIR)/$(WWWROOT_PATH)/help
	mkdir -p $(TARGETDIR)/$(WWWROOT_PATH)/cgi-bin
	install -m 644 $(addprefix ./html/, $(PAGES)) $(TARGETDIR)/$(WWWROOT_PATH)
	install -m 644 $(addprefix ./html/, $(CSS_PAGES)) $(TARGETDIR)/$(WWWROOT_PATH)/css
	install -m 644 $(addprefix ./html/, $(IMG_PAGES)) $(TARGETDIR)/$(WWWROOT_PATH)/img
	install -m 644 $(addprefix ./html/, $(HELP_PAGES)) $(TARGETDIR)/$(WWWROOT_PATH)/help
	install -m 644 $(addprefix ./html/, $(SCRIPT_PAGES)) $(TARGETDIR)/$(WWWROOT_PATH)/script
	install -m 644 $(addprefix ./html/, $(SCRIPT_PAGES)) $(TARGETDIR)/$(WWWROOT_PATH)/cgi-bin
	install -m 755 $(addprefix ./html/, $(CGI_BIN)) $(TARGETDIR)/$(WWWROOT_PATH)/cgi-bin
	$(STRIP) $(TARGETDIR)/www/cgi-bin/readycloud_control.cgi
	install -m 644 $(STR_TBL_FILE) $(TARGETDIR)/$(WWWROOT_PATH)

clean:


