#
# Copyright 2016  Hon Hai Precision Ind. Co. Ltd.
# All Rights Reserved.
# No portions of this material shall be reproduced in any form without the
# written permission of Hon Hai Precision Ind. Co. Ltd.
#
# All information contained in this document is Hon Hai Precision Ind.
# Co. Ltd. company private, proprietary, and trade secret property and
# are protected by international intellectual property laws and treaties.
#
# $Id$
#
#
#

CONFIG_ACOS_MODULES=y
CONFIG_ARNONAT=y
CONFIG_ACOSNAT=n
TELNET_ENABLE_FLAG=y
UPNP_ENABLE_FLAG=y
INTERNET_UPGRADE_FLAG=y
POT_ENABLE_FLAG=y
WAN_LAN_CONFLICT_ENABLE_FLAG=y
LLTD_ENABLE_FLAG=y
#Foxconn modified start, John Ou, 12/10/2014, for new debug page
INSTALL_NAT_CLI=n
#Foxconn modified end, John Ou, 12/10/2014, for new debug page
TRAFFIC_METER_FLAG=y
ACOS_TR069=n
UPNP_SMARTWIZARD_2_0=y
UPNP_SMARTWIZARD_3_0=y
UPNP_IGNORE_NEW_REGION=y
CONFIG_NEW_WANDETECT=y

CONFIG_NAT_4096_SESSION=y



ifeq ($(strip $(PROFILE)),D6300)
ENABLE_MWAN=n
ENABLE_VLAN=y
ENABLE_MLAN=n
ENABLE_VPN=y
SUPPORT_DUAL_BAND=y
STA_MODE=y
AP_MODE=y
CONFIG_TIMEMACHINE=n
CONFIG_RU_WAN_FLOW=y
CONFIG_RUSSIA_IPTV=y
INCLUDE_PNPX=y
CONFIG_REMOTE_SMB_CONF=y
CONFIG_USE_KERNEL_NTFS=y
CONFIG_ACCESSCONTROL=y
SKU=D6300
ENABLE_SCRATCHPAD_FLAG=y
CONFIG_XDSL_PRODUCT=y
endif

ifeq ($(strip $(PROFILE)),D6400)
ENABLE_MWAN=n
ENABLE_VLAN=y
ENABLE_MLAN=n
ENABLE_VPN=n
SUPPORT_DUAL_BAND=y
STA_MODE=y
AP_MODE=y
CONFIG_TIMEMACHINE=n
VLAN_SUPPORT=y
INCLUDE_PNPX=y
CONFIG_REMOTE_SMB_CONF=n
CONFIG_USE_KERNEL_NTFS=y
CONFIG_ACCESSCONTROL=y
CONFIG_OPENVPN=y
CONFIG_IMPLICIT_BEAMFORMING=y
CONFIG_USE_KERNEL_USB_PRINTER=y
SKU=D6400
CONFIG_DETECT_AP_MODE=n
INCLUDE_WIZ_LOG=y
INCLUDE_CONSOLE_LOG=y
ENABLE_SCRATCHPAD_FLAG=y
CONFIG_XDSL_PRODUCT=y
endif

ifeq ($(strip $(PROFILE)),D6220)
ENABLE_MWAN=n
ENABLE_VLAN=y
ENABLE_MLAN=n
ENABLE_VPN=n
SUPPORT_DUAL_BAND=y
STA_MODE=y
AP_MODE=y
CONFIG_TIMEMACHINE=n
VLAN_SUPPORT=y
INCLUDE_PNPX=y
CONFIG_REMOTE_SMB_CONF=n
CONFIG_USE_KERNEL_NTFS=y
CONFIG_ACCESSCONTROL=y
CONFIG_OPENVPN=y
CONFIG_IMPLICIT_BEAMFORMING=y
CONFIG_USE_KERNEL_USB_PRINTER=y
SKU=D6220
CONFIG_DETECT_AP_MODE=n
INCLUDE_WIZ_LOG=y
INCLUDE_CONSOLE_LOG=y
ENABLE_SCRATCHPAD_FLAG=y
CONFIG_XDSL_PRODUCT=y
endif

ifeq ($(PROFILE),D7000v2)
ENABLE_MWAN=n
ENABLE_VLAN=y
ENABLE_MLAN=n
CONFIG_INTEL_SDK=y
CONFIG_INTEL_PRODUCT=y
STA_MODE=y
AP_MODE=y
CONFIG_TIMEMACHINE=n
VLAN_SUPPORT=y
INCLUDE_PNPX=y
CONFIG_USE_KERNEL_NTFS=y
CONFIG_ACCESSCONTROL=y
CONFIG_OPENVPN=y
CONFIG_IMPLICIT_BEAMFORMING=y
CONFIG_USE_KERNEL_USB_PRINTER=y
CONFIG_DETECT_AP_MODE=n
INCLUDE_WIZ_LOG=y
INCLUDE_CONSOLE_LOG=y
ENABLE_SCRATCHPAD_FLAG=n
CONFIG_XDSL_PRODUCT=n
CONFIG_ADMIN_ACCOUNT=y
CONFIG_REMOTE_USB_PROTECT=y
CONFIG_BONJOUR_PRINTER=y
#Foxconn Perry added start, 2011/11/18, for remote_smb_conf
CONFIG_REMOTE_SMB_CONF=y
#Foxconn added start by Kathy, 11/04/2013 @ remote_user_conf 
CONFIG_REMOTE_USER_CONF=y
#Foxconn added end by Kathy, 11/04/2013 @ remote_user_conf
CONFIG_USERSETUP=y
endif


ifeq ($(PROFILE),D6220v2)
ENABLE_MWAN=n
ENABLE_VLAN=y
ENABLE_MLAN=n
CONFIG_INTEL_SDK=y
CONFIG_INTEL_PRODUCT=y
STA_MODE=y
AP_MODE=y
CONFIG_TIMEMACHINE=n
VLAN_SUPPORT=y
INCLUDE_PNPX=y
CONFIG_REMOTE_SMB_CONF=n
CONFIG_USE_KERNEL_NTFS=y
CONFIG_ACCESSCONTROL=y
CONFIG_OPENVPN=y
CONFIG_IMPLICIT_BEAMFORMING=y
CONFIG_USE_KERNEL_USB_PRINTER=y
CONFIG_DETECT_AP_MODE=n
INCLUDE_WIZ_LOG=y
INCLUDE_CONSOLE_LOG=y
ENABLE_SCRATCHPAD_FLAG=n
CONFIG_XDSL_PRODUCT=n
CONFIG_ADMIN_ACCOUNT=y
CONFIG_REMOTE_USB_PROTECT=y
CONFIG_BONJOUR_PRINTER=y
endif

CONFIG_OPENDNS=y
MULTIPLE_SSID_ENABLE_FLAG=y

MULTI_LANG_ENABLE=y
SAMBA_ENABLE_FLAG=y

USB_NEW_SPEC_FLAG=y
HTTP_ACCESS_USB_FLAG=y
FTP_ACCESS_USB_FLAG=y

DSL_SPEC_V1_0=y

ENABLE_HTTPS_FLAG=y
BRCM_PLATEFORM=y

ENABLE_PORT_MIRRORING=n
ENABLE_OSGI=n
CONFIG_DLNA=y

CONFIG_OPENSSL=y

CONFIG_ROUTER_SPEC_1_8=y

CONFIG_RESTART_ALL_PROCESS=y

CONFIG_BURNSKU=y
CONFIG_GET_ST_CHKSUM=y


CONFIG_BURNSKU=y
CONFIG_GET_ST_CHKSUM=y
INCLUDE_IPV6_FLAG=y
ENABLE_DSL_FW_RULE=y
ENABLE_MCPD_FLAG=y

ENABLE_IGMP_PROXY=y

ENABLE_CDLESS=y

DPF_ENABLE_FLAG=n
CONFIG_NTP_SYNC_RECORD=y
CONFIG_QOS_AUTO_CHECK_BW=n
CONFIG_WL_ACCESS_RECORD=y
NEW_FORWARD_SPEC=y
CONFIG_WPS_V20=y
PARSER_ENABLE=y
CONFIG_SOAP_API_20=y
#added Dennis 01/02/2013, for ap mode detection
CONFIG_HIDDEN_PAGE_DEBUG=y
CONFIG_NEW_DEBUG_HIDDEN_PAGE=y
IPTV6RD_ENABLE_FLAG=y
CONFIG_CLOUD_XAGENT_CONF=y

##For ACOS NAT
CONFIG_IOCTL_NO_POINTER=y

CONFIG_READYCLOUD_NEW_PATH=y

